style='E:\\codes\\m2tw\\plugins\\luaPlugin\\docs\\ldocTheme'
dir='E:\\codes\\m2tw\\plugins\\luaPlugin\\docs\\generatedLuaDocs'
file = {'luaP.cpp','luaP2.cpp','luaEvents.cpp'}
merge=true
format ='markdown'
project = '<a href="https://youneuoy.github.io/M2TWEOP-library/">M2TWEOP</a>'
description='Project, created to expand M2TW engine'
one=true
title='M2TW Engine Overhaul Project'
use_markdown_titles=true
readme = {'E:/codes/m2tw/plugins/luaPlugin/docs/README_IMGUI.md'}