style='./ldocTheme'
dir='./generatedLuaDocs'
file = {'../mapleLib/scriptingDocsTesting.cpp'}
file = {'../luaPlugin/luaP.cpp','../luaPlugin/luaEopEdu.cpp','../luaPlugin/luaP2.cpp','../luaPlugin/luaEvents.cpp'}
merge=true
format ='markdown'
project = 'M2TWEOP\nscripting'
description='Project, created to expand M2TW engine'
kind_names={topic='Extra',module='Modules'}
one=true
title='M2TW Engine Overhaul Project'
use_markdown_titles=true
not_luadoc=true
readme = {'./README_IMGUI.md'}